const $=s=>document.querySelector(s),chat=$('#chat'),input=$('#input'),send=$('#send'),mic=$('#mic'),status=$('#status');
const KEY='aria_ultimate_v1';let state=JSON.parse(localStorage.getItem(KEY)||'null')||{messages:[],memory:'',web:true,speak:false,highImage:true,token:''};let controller=null,editData='';
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){chat.innerHTML='';if(!state.messages.length){chat.innerHTML='<section class="welcome"><div class="hero-orb">A</div><h1>سلام، من آریا هستم</h1><p>دستیار شخصی هوشمند تو؛ گفتگو، وب، صدا و استودیو تصویر.</p><div class="chips"><button class="chip">یک ایده خلاقانه برای من بساز</button><button class="chip">آخرین اطلاعات را بررسی کن</button><button class="chip">یک تصویر سینمایی بساز</button></div></section>';return}for(const m of state.messages){const d=document.createElement('article');d.className='msg '+m.role;const b=document.createElement('div');b.className='bubble';b.textContent=m.content;d.append(b);if(m.image){const im=document.createElement('img');im.className='generated';im.src=m.image;im.alt='ARIA';d.append(im)}if(m.role==='assistant'){const a=document.createElement('div');a.className='msg-actions';const c=document.createElement('button');c.textContent='کپی';c.onclick=()=>navigator.clipboard?.writeText(m.content);a.append(c);d.append(a)}chat.append(d)}chat.scrollTop=chat.scrollHeight}
function add(role,content,image=''){state.messages.push({role,content,image,at:Date.now()});save();render()}
function headers(){const h={'content-type':'application/json'};if(state.token)h.authorization='Bearer '+state.token;return h}
function busy(v){send.disabled=v;input.disabled=v;mic.disabled=v;status.textContent=v?'در حال پردازش…':'آماده‌ام'}
async function ask(text){text=text.trim();if(!text||send.disabled)return;add('user',text);input.value='';input.style.height='auto';busy(true);controller=new AbortController();try{const r=await fetch('/api/chat',{method:'POST',headers:headers(),signal:controller.signal,body:JSON.stringify({messages:state.messages.map(({role,content})=>({role,content})),memory:state.memory,webSearch:state.web})});const j=await r.json();if(!r.ok)throw Error(j.error||'خطا');add('assistant',j.text);if(state.speak)speak(j.text)}catch(e){if(e.name!=='AbortError')add('assistant','خطا: '+e.message)}finally{controller=null;busy(false)}}
send.onclick=()=>ask(input.value);input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,150)+'px'});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(input.value)}});document.addEventListener('click',e=>{if(e.target.classList.contains('chip'))ask(e.target.textContent)});
function speak(t){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='fa-IR';u.rate=.98;speechSynthesis.speak(u)}}function syncVoice(){ $('#voiceOut').textContent=state.speak?'🔊':'🔇'}$('#voiceOut').onclick=()=>{state.speak=!state.speak;save();syncVoice()};
let rec=null;if('SpeechRecognition'in window||'webkitSpeechRecognition'in window){const R=window.SpeechRecognition||window.webkitSpeechRecognition;rec=new R();rec.lang='fa-IR';rec.interimResults=false;rec.onstart=()=>{mic.classList.add('on');status.textContent='دارم گوش می‌دم…'};rec.onend=()=>{mic.classList.remove('on');status.textContent='آماده‌ام'};rec.onresult=e=>ask(e.results[0][0].transcript);rec.onerror=()=>status.textContent='میکروفون در دسترس نیست'}mic.onclick=()=>rec?rec.start():(status.textContent='تشخیص گفتار پشتیبانی نمی‌شود');
const panel=$('#panel');$('#settings').onclick=()=>{panel.classList.add('show');$('#web').checked=state.web;$('#speak').checked=state.speak;$('#highImage').checked=state.highImage;$('#memory').value=state.memory;$('#token').value=state.token};$('#close').onclick=()=>panel.classList.remove('show');$('#web').onchange=e=>{state.web=e.target.checked;save()};$('#speak').onchange=e=>{state.speak=e.target.checked;save();syncVoice()};$('#highImage').onchange=e=>{state.highImage=e.target.checked;save()};$('#memory').oninput=e=>{state.memory=e.target.value;save()};$('#token').oninput=e=>{state.token=e.target.value.trim();save()};$('#clear').onclick=()=>{if(confirm('گفتگو و حافظه محلی پاک شود؟')){state={messages:[],memory:'',web:true,speak:false,highImage:true,token:state.token};save();render();panel.classList.remove('show')}};$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='aria-memory.json';a.click()};$('#stop').onclick=()=>{controller?.abort();speechSynthesis?.cancel();busy(false)};
const imagePanel=$('#imagePanel');$('#imageBtn').onclick=()=>imagePanel.classList.add('show');$('#closeImage').onclick=()=>imagePanel.classList.remove('show');document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const edit=t.dataset.tab==='edit';$('#gen').hidden=edit;$('#edit').hidden=!edit});
$('#generateImage').onclick=async()=>{const prompt=$('#imagePrompt').value.trim();if(!prompt)return;const b=$('#generateImage');b.disabled=true;b.textContent='در حال ساخت…';$('#imageResult').innerHTML='';try{const r=await fetch('/api/image',{method:'POST',headers:headers(),body:JSON.stringify({prompt,size:$('#imageSize').value})});const j=await r.json();if(!r.ok)throw Error(j.error||'خطا');const im=document.createElement('img');im.className='generated large';im.src=j.image;$('#imageResult').append(im);add('assistant','تصویر ساخته شد.',j.image)}catch(e){$('#imageResult').textContent='خطا: '+e.message}finally{b.disabled=false;b.textContent='ساخت تصویر'}};
$('#editFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{editData=r.result;$('#editPreview').src=editData;$('#editPreview').hidden=false};r.readAsDataURL(f)};
$('#editImage').onclick=async()=>{const prompt=$('#editPrompt').value.trim();if(!editData||!prompt)return;const b=$('#editImage');b.disabled=true;b.textContent='در حال ویرایش…';$('#imageResult').innerHTML='';try{const r=await fetch('/api/image-edit',{method:'POST',headers:headers(),body:JSON.stringify({prompt,image:editData})});const j=await r.json();if(!r.ok)throw Error(j.error||'خطا');const im=document.createElement('img');im.className='generated large';im.src=j.image;$('#imageResult').append(im);add('assistant','تصویر با موفقیت ویرایش شد.',j.image)}catch(e){$('#imageResult').textContent='خطا: '+e.message}finally{b.disabled=false;b.textContent='ویرایش تصویر'}};
fetch('/api/health').then(r=>r.json()).then(h=>{if(!h.configured)status.textContent='OPENAI_API_KEY تنظیم نشده';else if(h.privateMode&&!state.token)status.textContent='توکن خصوصی لازم است'}).catch(()=>status.textContent='اتصال به سرور برقرار نیست');if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});render();syncVoice();
