const API=localStorage.getItem('ARIA_API_URL')||'/v1/chat';
const chat=document.querySelector('#chat'), input=document.querySelector('#input'), send=document.querySelector('#send'), mic=document.querySelector('#mic'), status=document.querySelector('#status');
let messages=JSON.parse(localStorage.getItem('aria_messages')||'[]');
let memory=JSON.parse(localStorage.getItem('aria_memory')||'[]');
function render(){chat.innerHTML=''; if(!messages.length){chat.innerHTML='<div class="empty"><h1>سلام رفیق ❤️</h1><div>من ARIA هستم. هر چیزی که لازم داری بگو.</div></div>';return} for(const m of messages){const d=document.createElement('div');d.className='msg '+m.role;d.textContent=m.content;chat.appendChild(d)} chat.scrollTop=chat.scrollHeight}
function save(){localStorage.setItem('aria_messages',JSON.stringify(messages.slice(-100)));localStorage.setItem('aria_memory',JSON.stringify(memory.slice(0,50)))}
function add(role,content){messages.push({role,content});save();render()}
async function ask(){const text=input.value.trim();if(!text)return;input.value='';add('user',text);status.textContent='در حال فکر کردن…';send.disabled=true;try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages,memory})});const data=await r.json();if(!r.ok)throw Error(data.error||'خطا');add('assistant',data.reply);speak(data.reply)}catch(e){add('assistant','رفیق، اتصال به سرور برقرار نشد. آدرس API و اتصال اینترنت را بررسی کن.');}finally{send.disabled=false;status.textContent='آماده‌ام، رفیق 🤝'}}
send.onclick=ask;input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}});
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(SR){rec=new SR();rec.lang='fa-IR';rec.interimResults=false;rec.onstart=()=>{mic.classList.add('recording');status.textContent='دارم گوش می‌دهم…'};rec.onend=()=>{mic.classList.remove('recording');status.textContent='آماده‌ام، رفیق 🤝'};rec.onresult=e=>{input.value=e.results[0][0].transcript;ask()};mic.onclick=()=>{try{rec.start()}catch{}}}else mic.onclick=()=>alert('تشخیص گفتار این مرورگر در دسترس نیست.');
function speak(t){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='fa-IR';u.rate=1.02;speechSynthesis.speak(u)}
document.querySelector('#memoryBtn').onclick=()=>{document.querySelector('#memory').value=memory.join('\n');document.querySelector('#panel').classList.add('show')};document.querySelector('#closeMemory').onclick=()=>document.querySelector('#panel').classList.remove('show');document.querySelector('#saveMemory').onclick=()=>{memory=document.querySelector('#memory').value.split('\n').map(x=>x.trim()).filter(Boolean);save();document.querySelector('#panel').classList.remove('show')};
if('serviceWorker'in navigator) navigator.serviceWorker.register('./sw.js');render();
