plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'ir.yasin.hamhoosh'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.yasin.hamhoosh'
        minSdk 26
        targetSdk 35
        versionCode 12
        versionName '1.2.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation 'dev.ffmpegkit-maintained:llama-android:0.1.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
}
